language: objective-c
osx_image: xcode11
node_js: 10
before_install:
- openssl aes-256-cbc -K $encrypted_a43c9d4ca4d4_key -iv $encrypted_a43c9d4ca4d4_iv
  -in dist.p12.enc -out scripts/travis/dist.p12 -d
- security create-keychain -p mysecretpassword build.keychain
- security default-keychain -s build.keychain
- security unlock-keychain -p mysecretpassword build.keychain
- security set-keychain-settings -t 3600 -u build.keychain
- security import ./scripts/travis/dist.p12 -k build.keychain -T /usr/bin/codesign
  -P ""
- 'security set-key-partition-list -S apple-tool:,apple: -s -k mysecretpassword build.keychain'
install:
- bash install_dependency.sh
- cd $TRAVIS_BUILD_DIR/ClashX
- echo `go version`
- brew update
- brew upgrade go || true
- echo `go version`
- python3 build_clash.py
- cd $TRAVIS_BUILD_DIR

script:
- 'set -o pipefail && xcodebuild -workspace ClashX.xcworkspace -scheme "ClashX" build CODE_SIGN_IDENTITY="Developer
  ID Application: Fuzhou West2Online Internet Inc. (MEWHFZ92DY)"|xcpretty'
- echo "Checking SMJobBless Vailded"
- build_dir=`xcodebuild -workspace ClashX.xcworkspace -scheme "ClashX" -showBuildSettings -configuration Debug | grep -m 1 "TARGET_BUILD_DIR" | grep -oEi "\/.*"`
- build_dir=${build_dir}"/ClashX.app"
- python SMJobBlessUtil.py check ${build_dir}
- echo "Check completed"

before_deploy:
- gem install gym
- bundle install
- fastlane gym -s ClashX
- npm install --global create-dmg
- create-dmg ClashX.app
- mv ClashX*.dmg ClashX.dmg
- fastlane run notarize package:"./ClashX.dmg" bundle_id:"com.west2online.ClashX"

deploy:
  provider: releases
  prerelease: false
  skip_cleanup: true
  api_key:
    secure: lXnU9/uNlKKyK2t9dLTLgVGebKi7A6trSIV7cnV3QdGVTqBR5bbF9HD4OY2K0gdO3IMdgMNLhx4k42K67mOgZzb/pQtw3QaK8Zs7uCj1DpmnkX37UgrDLx4eDfVI84VqmOIpfQBRby8FsmDYIz6x1YCVq588MaZaFl0BvnDGbSX+xaQ41z1O6rS0zbh+FAhGCinr/kmBuWqUYRscwCUNOiNrDfz0zXN93bvGSzicLkQUFJs23YM4B0LZGsEBDNHRoHBVGj95MtHEGu+GY6DgeoFFJKczdwfqQb1mL9GSyZWZuldTzykQZY7rB7h7tRCOI5bEzgAa8TX9osa8SnnYYpMe2aLKWloOORzVC9cBb/I4PnbrT494mAwrjWQcqc92iKiHkmQOVPht9ch8dvvwuf9zLWWAUvIr/ZLAjno2oCHrr+4Jh0NBjDm56qBDX+xLawWj5bM+M3UzLlfotGsvLLTwKCP02u9ynAWjFB69ZdP6NZJyz5R8iKFlBkIDgWbII/20EoZ3JpgFms8lxW4i0WkCDuhpvy6lwSPsUm1ncwT4VrRPbe8y126xHMISTMNq3aqmyqtjgxJSySv1KEPtjb3y3ymtN93DxKUN+tVA7slImXe8BBmVy+AWfpeItUYX6KgJDgEii+umZxuEw/8Isr99MAND63uCm0gY9gvPc0U=
  file: 
    - ClashX.dmg

  on:
    repo: frainzy1477/clashX
    branch: master
    tags: true 
 
after_deploy:
- 'curl -u frainzy1477:$GitHub_Token -X POST https://api.github.com/repos/frainzy1477/clashX/pages/builds -H "Accept: application/vnd.github.mister-fantastic-preview+json"'
- fastlane run upload_symbols_to_crashlytics
