name: CI

on: [push]

jobs:
  build:

    runs-on: macOS-latest

    env:
      CODE_SIGN_IDENTITY: "Developer ID Application: Fuzhou West2Online Internet Inc. (MEWHFZ92DY)"
    steps:
    - uses: actions/checkout@v1
    - name: import certs
      run: |
        openssl aes-256-cbc -k  "${{ secrets.ENCRYPTION_SECRET }}" -in ".github/certs/dist.p12.enc" -d -a -out ".github/certs/dist.p12"
        security create-keychain -p mysecretpassword build.keychain
        security default-keychain -s build.keychain
        security unlock-keychain -p mysecretpassword build.keychain
        security set-keychain-settings -t 3600 -u build.keychain
        security import "./.github/certs/dist.p12" -k build.keychain -T /usr/bin/codesign -P ""
        bash .github/enableKeyChain.sh
        

    - name: install_dependency
      run: |
        bash install_dependency.sh
        cd ClashX
        # brew update
        # brew upgrade go || true
        echo `go version`
        python3 build_clash.py

    - name: build and check
      run: |
        echo $CODE_SIGN_IDENTITY
        set -o pipefail && xcodebuild -workspace ClashX.xcworkspace -scheme "ClashX" build |xcpretty
        echo "Checking SMJobBless Vailded"
        build_dir=`xcodebuild -workspace ClashX.xcworkspace -scheme "ClashX" -showBuildSettings -configuration Debug | grep -m 1 "TARGET_BUILD_DIR" | grep -oEi "\/.*"`
        build_dir=${build_dir}"/ClashX.app"
        python SMJobBlessUtil.py check ${build_dir}

